apiVersion: v1
kind: Service
metadata:
  name: prod
  namespace: k8ssimple
spec:
  selector:
    k8ssimple-service: prod
  externalIPs: []
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: []
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
