apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod
  labels:
    k8ssimple-cluster: prod
  namespace: k8ssimple
spec:
  replicas: 2
  selector:
    matchLabels:
      k8ssimple-cluster: prod
  template:
    metadata:
      labels:
        k8ssimple-cluster: prod
        k8ssimple-service: prod
    spec:
      containers:
      - image: gcr.io/spinnaker-1022/k8ssimple:release
        name: k8ssimple-prod
        ports:
        - containerPort: 80

